json_input_messages: src/pipe_gaps/assets/sample_data/sample_messages_lines.json
ssvids: []
date_range: ["2024-01-01", "2024-01-02"]
min_gap_length: 1.2
n_hours_before: 12
window_period_d: 1
skip_open_gaps: true
save_json: true

project: world-fishing-827
